export enum ErrorCode {
  // NOT FOUND / MISSING / REQUIRED
  REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND",
  BLOGGER_NOT_FOUND = "BLOGGER_NOT_FOUND",
  MEAL_NOT_FOUND = "MEAL_NOT_FOUND",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  RECOMMENDATION_NOT_FOUND = "RECOMMENDATION_NOT_FOUND",
  NO_MEALS_FOR_RESTAURANT = "NO_MEALS_FOR_RESTAURANT",
  AT_LEAST_ONE_LOCATION_REQUIRED = "AT_LEAST_ONE_LOCATION_REQUIRED",
  NAME_IS_REQUIRED = "NAME_IS_REQUIRED",
  MISSING_GOOGLE_ID_OR_PHONE = "MISSING_GOOGLE_ID_OR_PHONE",
  PASSWORDS_REQUIRED = "PASSWORDS_REQUIRED",
  NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED",
  LOCATIONS_REQUIRED = "LOCATIONS_REQUIRED",
  MISSING_DATA = "MISSING_DATA",
  CATEGORIES_REQUIRED = "CATEGORIES_REQUIRED",

  // EXPIRED / INCORRECT / INVALID
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  INCORRECT_CURRENT_PASSWORD = "INCORRECT_CURRENT_PASSWORD",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_OTP = "INVALID_OTP",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER",
  ORIGINALLY_REGISTERED_WITH_GOOGLE = "ORIGINALLY_REGISTERED_WITH_GOOGLE",
  INVALID_ROLE = "INVALID_ROLE",
  CANT_CREATE_SUPER_ADMIN = "CANT_CREATE_SUPER_ADMIN",
  INVALID_TOKEN = "INVALID_TOKEN",
  DATA_SHOULD_BE_MULTIPLE = "DATA_SHOULD_BE_MULTIPLE",
  INVALID_RATING = "INVALID_RATING",
  INVALID_DATE = "INVALID_DATE",
  INVALID_LOCATIONS = "INVALID_LOCATIONS",

  // ALREADY EXISTS
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  BLOGGER_ALREADY_EXISTS = "BLOGGER_ALREADY_EXISTS",
  MEAL_ALREADY_EXISTS = "MEAL_ALREADY_EXISTS",
  RESTAURANT_ALREADY_EXISTS = "RESTAURANT_ALREADY_EXISTS",
  RECOMMENDATION_ALREADY_EXISTS = "RECOMMENDATION_ALREADY_EXISTS",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
  PHONE_ALREADY_REGISTERED = "PHONE_ALREADY_REGISTERED",

  ACCESS_DENIED = "ACCESS_DENIED",

  ONE_OR_MANY_MEAL_BELONG_TO_ANOTHER_RESTAURANT = "ONE_OR_MANY_MEAL_BELONG_TO_ANOTHER_RESTAURANT",
  ONE_OR_MANY_RECOMMENDATION_BELONG_TO_ANOTHER_RESTAURANT = "ONE_OR_MANY_RECOMMENDATION_BELONG_TO_ANOTHER_RESTAURANT",
  EMAIL_CANNOT_BE_EDITED = "EMAIL_CANNOT_BE_EDITED"
}
